= judo-snapshot-checker-maven-plugin

Snapshot tests are a very useful tool whenever you want to make sure your code does not change unexpectedly.

A typical snapshot test takes a source file, then compares it to a reference snapshot file.
The test will fail if the two snapshots do not match: either the change is unexpected, or the reference snapshot needs
to be updated to the new version of the code.

== Usage

[source,xml]
----
<plugin>
    <groupId>hu.blackbelt.judo.generator</groupId>
    <artifactId>judo-snapshot-checker-maven-plugin</artifactId>
    <version>${revision}</version>
    <executions>
        <execution>
            <goals>
                <goal>checkSnapshots</goal>
            </goals>
            <phase>generate-sources</phase>
        </execution>
    </executions>
    <configuration>
        <sourceDirectory>${project.basedir}/target/frontend-react/</sourceDirectory>
        <snapshotDirectory>${project.basedir}/src/test/resources/snapshots/frontend-react/</snapshotDirectory>
        <sources>
            <source>src/pages/God/God/Galaxies/AccessViewPage/index.tsx</source>
            <source>src/pages/God/God/Galaxies/AccessTablePage/index.tsx</source>
            <!-- etc... -->
        </sources>
    </configuration>
</plugin>
----

== Configuration

=== createSnapshotIfNotExists

(Optional, default: `true`)

The plugin will automatically create snapshot files if they do not exist, unless the `createSnapshotIfNotExists`
configuration is explicitly set to `false`;

=== forceSnapshotOverwrite

(Optional, default: `false`)

If you would like the plugin to always update the contents of snapshot files before checking, set this to `true`.

Setting it to true can be useful if you are e.g. doing refactors and do not intend to have any changes in your snapshot.

=== snapshotPostfix

(Optional, default: `".snapshot"`)
