= judo-snapshot-checker-maven-plugin

The intention behind this plugin is to help prevent regressions by

- tracking desired generated files and their contents
- provide info for every change so that developers can determine what change is intended and what is not

== Usage

[source,xml]
----
<plugin>
    <groupId>hu.blackbelt.judo.generator</groupId>
    <artifactId>judo-snapshot-checker-maven-plugin</artifactId>
    <version>${revision}</version>
    <executions>
        <execution>
            <goals>
                <goal>checkSnapshots</goal>
            </goals>
            <phase>generate-sources</phase>
        </execution>
    </executions>
    <configuration>
        <sourceDirectory>${project.basedir}/target/frontend-react/</sourceDirectory>
        <snapshotDirectory>${project.basedir}/src/test/resources/snapshots/frontend-react/</snapshotDirectory>
        <sources>
            <source>src/pages/God/God/Galaxies/AccessViewPage/index.tsx</source>
            <source>src/pages/God/God/Galaxies/AccessTablePage/index.tsx</source>
            <!-- etc... -->
        </sources>
    </configuration>
</plugin>
----

== Configuration

=== createSnapshotIfNotExists

(Optional, default: `true`)

The plugin will automatically create snapshot files if they do not exist, unless the `createSnapshotIfNotExists`
configuration is explicitly set to `false`;

=== forceSnapshotOverwrite

(Optional, default: `false`)

If you would like the plugin to always update the contents of snapshot files before checking, set this to `true`.

Setting it to true can be useful if you are e.g. doing refactors and do not intend to have any changes in your snapshot.

=== snapshotPostfix

(Optional, default: `".snapshot"`)
